---
title: "FPM #5: Flash Talk"
subtitle: "Assigned Wed 03/11/2026 | Due TBD"
---

::: {.callout-note}
FPM #5 is the the fifth (and final!) step in working towards your [final project](final-project.qmd){target="_blank"}, which is meant to combine nearly all of the course [learning outcomes](final-project.qmd#LOs){target="_blank"}. **You'll prepare and present your work to your instructors and peers in short flash talks.**
:::

## Description {#description} 

### I. Present you infographic {#partI}

[**These 3-minute flash talks are an opportunity to showcase and celebrate all your hard work this quarter, and learn from the diverse and creative work of your peers {{< fa face-grin-wide >}}**]{.teal-text}

Flash talks will take place **in person during finals week**. You will have **3 minutes** to present your final infographic. Your goal is to help your audience understand both what your infographic reveals and how you brought it to life. You should be prepared to briefly discuss:

- [ ] **your goal:** what is the main goal or message your infographic was designed to illuminate?
- [ ] **your data:** what data source(s) did you use, and why were they appropriate for addressing your goal or questions?
- [ ] **your insights:** what are two key takeaways that you want your audience to learn and remember from your infographic?
- [ ] **your design decisions:** highlight two or three intentional design choices (e.g., color, typography, layout, or chart type) that strengthened the cohesiveness and clarity of your infographic’s story
- [ ] **your process:** describe one or two challenges that you encountered and how you addressed or iterated on these issues
- [ ] **your reflection:** share one or two things you’re especially proud of completing, learning, or accomplishing for this project 

***No need to prepare slides** -- you'll be pulling up your blog post from [this Google Sheet](https://docs.google.com/spreadsheets/d/1eCGNK4Bl2QHXZ0ucs0wYegm1BiNo9RyI8r17DyrNgM4/edit?gid=0#gid=0){target="_blank"} to show off your infographic while you talk.*

::: {.callout-important}
## **IMPORTANT: You are expected to present *in person*** 
Make up presentations will not be permitted. Please plan accordingly!
:::

## Rubric (specifications) {#rubric}

- [ ] **Present a 3-minute flash talk, in person** during our assigned finals week time slot. Your talk should briefly address each of the six points as described in Part I.
- [ ] **Submit a [Generative AI Statement of Use](https://forms.gle/uCw7U5jzJAKahjA4A){target="_blank}** for FPM #5 by 1:00pm on 03/19/2026.