---
title: "Pre-course self reflection (SR #1)"
subtitle: "Assigned Wed 01/07/2026 | Due Fri 01/09/2026"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
---

## Description {#description}

[**In this self reflection, you'll come up with a plan for what you'd like to get out of the class and roughly outline how you'll accomplish your goals throughout the quarter.**]{.teal-text} You'll continue revisiting the goals you set for yourself in this assignment throughout the quarter, so its worthwhile to be reflective!

### I. Create a repository using the `eds240-sr1` template {#partI}

[**Follow [these instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template#creating-a-repository-from-a-template){target="_blank"} to create a repository from the [`eds240-SR1` template](https://github.com/EDS-240-Data-Viz/eds240-sr1){target="_blank"}.**]{.teal-text} The template repository includes `SR1.qmd`, where you'll be responding to the self reflection prompts in the following section(s).

### II. Outline your learning goals and plan {#partII}

[**Please answer the following in `SR1.qmd`:**]{.teal-text}

- [ ] **1.** Which learning goals from the syllabus are you most excited about? 
- [ ] **2.** What do you hope to get out of this class?
- [ ] **3.** How do you plan on accomplishing your learning goals for this course? **Note:** be specific here! Instead of writing, “I will complete homework assignments” or “I will study,”  you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc. 

### III. (Optional) Help me get to know you a bit better! {#partIII}

::: {.callout-important}
Answering the following questions is completely optional, and your choice to do so (or not) won’t impact your assignment score. However, I do truly appreciate any reflections you choose to share!

**Please delete any questions you choose not to respond to from your `SR1.qmd` template.**
:::

[**I recognize that everyone is participating under unique circumstances. To best support you in this class, I'd love to learn more about your learning contexts. If you have the capacity and are interested in sharing, please answer any or all of the following:**]{.teal-text}

- [ ] **1.** Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I've been working in industry X for Y years”)? 
- [ ] **2.** If you have a particular career goal in mind, how does this course apply to your future career, if at all?
- [ ] **3.** What do you wish your instructors knew about you, but don't?
- [ ] **4.** What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them?
- [ ] **5.** How confident do you feel in your data visualization skills? Why?
- [ ] **6.** How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why? 
- [ ] **7.** What have you struggled with in the past in other graduate-level courses? Why?
- [ ] **8.** Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding?
- [ ] **9.** What responsibilities do you have outside of school, and how do you want to balance them?
- [ ] **10.** What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy? 
- [ ] **11.** What is a piece of media you enjoyed recently (e.g. music, book, movie, meme)? 

## Rubric (specifications) {#rubric}

To receive a "Satisfactory" on SR #1:

- [ ] **Answer all Part II questions using the Part I template.** There are no strict length requirements for free-response questions, however we expect that you answer them thoughtfully and fully.
- [ ] **Render `SR1.qmd` as a PDF.** Double check that all of your prose is appropriately formatted and that you've added your name to the `author` option in the document YAML.
- [ ] **Upload your PDF to Gradescope** by 11:59pm on Fri 01/09/2026.
- [ ] **Submit a [Generative AI Statement of Use](https://forms.gle/uCw7U5jzJAKahjA4A){target="_blank}** for SR #1 by 11:59pm on Fri 01/09/2026.
