---
title: "Mid-course self reflection (SR #2)"
subtitle: "Assigned Wed 02/04/2026 | Due Fri 02/06/2026"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS"
---

## Description {#description}

[**For this self reflection, revisit your initial learning goals and plans (from SR #1), then consider your progress towards those goals in your responses to the following questions:**]{.teal-text} 

## I. Create a repository using the `eds240-sr2` template {#partI}

[**Follow [these instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template#creating-a-repository-from-a-template){target="_blank"} to create a repository from the [`eds240-SR2` template](https://github.com/EDS-240-Data-Viz/eds240-sr2){target="_blank"}.**]{.teal-text} The template repository includes `SR2.qmd`, where you'll be responding to the self reflection prompts in the following section(s).

### II. Reflect on your progress {#partII}

[**Please answer the following in `SR2.qmd`:**]{.teal-text}

- [ ] **1.** How have you progressed towards your learning goals for this course? 
- [ ] **2.** What skills are you proud of developing? 
- [ ] **3.** If you've needed help, how have you sought it out? If you haven't sought out help, why not?
- [ ] **4.** Looking forward, how have your learning goals changed? Have they stayed the same? 
- [ ] **5.** What topics have excited you the most (so far)? Have you spent time or efforts outside of class and / or the assignments diving deeper into any of these topics? If yes, what did you learn?

### III. (Optional) Share any feedback you might have about the class {#partIII}

::: {.callout-important}
Answering the following questions is completely optional, and your choice to do so (or not) won’t impact your assignment score. That said, I truly appreciate any feedback you’re willing to share, and I take it into consideration as we move into the second half of the course.

**Please delete any questions you choose not to respond to from your `SR2.qmd` template.**
:::

- [ ] **1.** How would you change the structure of this course, if at all? If you wouldn't, what in particular about the structure has been working well for you?
- [ ] **2.** Is there anything about this course that you are really enjoying? Anything that isn't working for you? 
- [ ] **3.** What else would you like me to know about your experience in the course thus far? 

## Rubric (specifications) {#rubric}

To receive a "Satisfactory" on SR #2:

- [ ] **Answer all Part II questions using the Part I template.** There are no strict length requirements for free-response questions, however we expect that you answer them thoughtfully and fully.
- [ ] **Render `SR2.qmd` as a PDF.** Double check that all of your prose is appropriately formatted and that you've added your name to the `author` option in the document YAML.
- [ ] **Upload your PDF to Gradescope** by 11:59pm on Fri 02/06/2026.
- [ ] **Submit a [Generative AI Statement of Use](https://forms.gle/uCw7U5jzJAKahjA4A){target="_blank}** for SR #2 by 11:59pm on Fri 02/06/2026.
