---
format: 
  revealjs:
    slide-number: true
    # code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - ../../meds-slides-styles.scss
editor_options: 
  chunk_output_type: console
---

## {#title-slide data-menu-title="Title Slide" background="#047C91"} 

[EDS 240: Lab 8]{.custom-title}

[*Peer feedback*]{.custom-subtitle}

<hr class="hr-dark-blue">

[Week 8 | February 25^th^, 2025]{.custom-subtitle3}

---

## {#high-level-feedback data-menu-title="High-level feedback"}

[Consider high-level feedback . . .]{.slide-title}

<hr>

::: {.center-text .body-text-m}
**where the focus is on whether a data visualization is accurate, relevant and understandable for the intended audience**
:::

<br>

  - does the visualization address the defined question? if so, how? if not, what's missing or confusing?
  - what important trends do you see? are your eyes drawn to them? if yes, how? if no, how can you better highlight them?
  - what other context might be helpful for understanding this visualization (maybe the author has already considered this for the final deliverable!)? 
  - is this visualization approachable for its intended audience? if yes, how so? if no, why not?
  - consider the graphic form -- does it make sense for these data types?
  
---

## {#detail-oriented-feedback data-menu-title="Detail-oriented feedback"}

[. . . and detail-oriented feedback:]{.slide-title}

<hr>

::: {.center-text .body-text-m}
**where the focus is on aesthetics choices (e.g. colors, typefaces, layout, themes, white space, etc.) and how those choices help to enhance / tell the story**
:::

<br>

  - is the color palette colorblind-friendly?
  - are colors used to convey any messages or overall theme? would you change them to improve this?
  - are the typefaces legible? do they contribute to the overall theme?
  - do elements look crunched or appropriately spaced out?
  - any non-data elements that should be moved or removed for clarity or simplicity?

. . . 

::: {.center-text .body-text-m}
**Remember:** all critiques should be accompanied by actionable recommendations for improvement!
:::

---

## {#exercise data-menu-title="Exercise"}

[With a partner:]{.slide-title}

<hr>

1. Take 10 minutes to review your partner's viz and jot down (in the notes section of their Google slide):
  - **1 thing you really love / find effective**
  - **1 piece of high-level feedback + suggest an alternative approach**
  - **1 piece of detailed-oriented feedback + suggest an alternative approach**
2. Spend 10 minutes exchanging feedback and discussing your visualizations

<br>

```{r}
countdown::countdown(
  minutes = 20,
  # left = 0, right = 0,
  # Fanfare when it's over
  play_sound = TRUE,
  color_border              = "#FFFFFF",
  color_text                = "#7aa81e",
  color_running_background  = "#7aa81e",
  color_running_text        = "#FFFFFF",
  color_finished_background = "#ffa07a",
  color_finished_text       = "#FFFFFF",
  font_size = "2em",
  )
```

. . .

[In the last ~25 minutes of section, we'll do a rapid fire share out of feedback. Please be prepared to share with the class:]{.body-text-m}

- **1 thing your partner really enjoyed and why**
- **1 thing your partner saw as an area for improvement + a suggested alternative**

---

## {#questions-stats data-menu-title="Questioning stats"}

[Data viz thought exercise of the week]{.slide-title}

<hr>

::: {.center-text .body-text-m}
Learn some simple tips on questioning, interpreting, and truly understanding what numbers are saying
:::

{{< video https://www.youtube.com/watch?v=Zwwanld4T1w width="100%" height="65%" >}}

::: {.footer}
Watch this on your own time!
:::

