---
format: 
  revealjs:
    slide-number: true
    # code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - ../../../meds-slides-styles.scss
editor_options: 
  chunk_output_type: console
---

## {#title-slide data-menu-title="Title Slide" background="#047C91"} 

[EDS 240: Discussion 5]{.custom-title}

[*Non-standard chart types*]{.custom-subtitle}

<hr class="hr-dark-blue">

[Week 5 | February 4^th^, 2024]{.custom-subtitle3}

---

## {#fundamental-charts data-menu-title="Fundamental charts"}

[We've covered a number of "fundamental charts"]{.slide-title2}

<hr>

:::: {.columns}
::: {.column width="50%"}
[**Distributions**]{.body-text-m}

- histograms
- density plots
- ridgeline plots
- box plots
- violin plots

[**Evolution**]{.body-text-m}

- line charts
- area plots
:::

::: {.column width="50%"}
[**Rankings**]{.body-text-m}

- bar plots
- lollipop plots
- dumbbell plots

[**Numeric relationships**]{.body-text-m}

- scatter plots
- 2d density plots
:::
::::

. . .

::: {.center-text}
Familiarity with these chart types and when it's appropriate to use them is super important! They appear often in scientific literature.
:::

. . . 

::: {.center-text}
But they only scratch the surface of data viz possibilities.
:::

---

But there are so many more!

- ternary plot

Ranking
- radar plot
- petal plot
- dot plot

Part to whole
- diverging bar chart
- waffle chart
- icon array
- donut chart
- treemap
- sunburst chart

Distribution
- radial histogram
- strip plot

Evolution
- stream graph
- bump chart
- barcode chart
- 





